"""Centralized-state dimensions and slices shared by MLP and HGTA critics."""

WRAPPED_OBSERVATION_DIM = 288
SUPPLEMENTAL_STATE_DIM = 6
GRID_BUS_COUNT = 14
GRID_BUS_DYNAMIC_FEATURE_DIM = 5
GRID_BUS_DYNAMIC_STATE_DIM = GRID_BUS_COUNT * GRID_BUS_DYNAMIC_FEATURE_DIM

SUPPLEMENTAL_STATE_SLICE = slice(288, 294)
GRID_BUS_DYNAMIC_STATE_SLICE = slice(294, 364)
CENTRALIZED_STATE_DIM = 364
